-- MySQL Script generated by MySQL Workbench
-- jue 21 feb 2019 12:11:00 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `idRol` INT(11) NOT NULL,
  `NomRol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `DNIUsu` VARCHAR(9) NOT NULL COMMENT '	',
  `PwdUsu` VARCHAR(45) NOT NULL,
  `NomUsu` VARCHAR(45) NOT NULL,
  `ApeUsu` VARCHAR(45) NOT NULL,
  `EmaUsu` VARCHAR(45) NOT NULL,
  `ConUsu` VARCHAR(9) NOT NULL,
  `IdRol` INT(11) NOT NULL,
  PRIMARY KEY (`DNIUsu`),
  INDEX `IdRol_idx` (`IdRol` ASC),
  CONSTRAINT `IdRol`
    FOREIGN KEY (`IdRol`)
    REFERENCES `mydb`.`ROLES` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TARIFA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TARIFA` (
  `idTar` INT NOT NULL,
  `NomTar` VARCHAR(45) NOT NULL,
  `PrecTar` DOUBLE NOT NULL,
  `MinTar` INT(11) NOT NULL,
  `MegTar` INT(11) NOT NULL,
  PRIMARY KEY (`idTar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GASTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GASTOS` (
  `idGas` INT(11) NOT NULL,
  `DNIUsu` VARCHAR(9) NOT NULL,
  `IdTar` INT(11) NOT NULL,
  `TfnGas` VARCHAR(45) NOT NULL,
  `MinGas` INT(11) NULL,
  `MegGas` INT(11) NULL,
  PRIMARY KEY (`idGas`),
  INDEX `DNIUsu_idx` (`DNIUsu` ASC),
  INDEX `IdTar_idx` (`IdTar` ASC),
  CONSTRAINT `DNIUsu`
    FOREIGN KEY (`DNIUsu`)
    REFERENCES `mydb`.`USUARIO` (`DNIUsu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdTar`
    FOREIGN KEY (`IdTar`)
    REFERENCES `mydb`.`TARIFA` (`idTar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
